import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export enum AppSetting {
    MonitoringWindowDays = 'antispam_monitoring_window_days',
    SlidingWindowSeconds = 'antispam_sliding_window_seconds',
    CrossChannelThreshold = 'antispam_cross_channel_threshold',
    AdminChannelName = 'antispam_admin_channel',
    ScheduledReportTime = 'antispam_scheduled_report_time',
    ScheduledReportEnabled = 'antispam_scheduled_report_enabled',
    ScheduledReportTimezone = 'antispam_scheduled_report_timezone',
    RateShortBurst = 'antispam_rate_short_burst',
    RateSustained = 'antispam_rate_sustained',
    AiProvider = 'antispam_ai_provider',
    AiApiKey = 'antispam_ai_api_key',
    AiModel = 'antispam_ai_model',
}

export const APP_SETTINGS: ISetting[] = [
    {
        id: AppSetting.MonitoringWindowDays,
        type: SettingType.NUMBER,
        packageValue: 42,
        required: true,
        public: false,
        i18nLabel: 'Monitoring Window (days)',
        i18nDescription: 'Track new users for this many days after account creation (default: 42 = 6 weeks)',
    },
    {
        id: AppSetting.SlidingWindowSeconds,
        type: SettingType.NUMBER,
        packageValue: 300,
        required: true,
        public: false,
        i18nLabel: 'Sliding Window (seconds)',
        i18nDescription: 'Time window for detecting duplicate/cross-channel messages (default: 300 = 5 min)',
    },
    {
        id: AppSetting.CrossChannelThreshold,
        type: SettingType.NUMBER,
        packageValue: 3,
        required: true,
        public: false,
        i18nLabel: 'Cross-Channel Threshold',
        i18nDescription: 'Number of distinct channels a duplicate must appear in to trigger action (default: 3)',
    },
    {
        id: AppSetting.AdminChannelName,
        type: SettingType.STRING,
        packageValue: 'antispam-admin',
        required: true,
        public: false,
        i18nLabel: 'Admin Channel Name',
        i18nDescription: 'Private channel name for admin alerts and bot interaction',
    },
    {
        id: AppSetting.ScheduledReportTime,
        type: SettingType.STRING,
        packageValue: '18:00',
        required: true,
        public: false,
        i18nLabel: 'Scheduled Report Time (HH:MM)',
        i18nDescription: 'Time of day (24h format) to send the daily spam report in the selected timezone (e.g., 18:00 for 6 PM)',
    },
    {
        id: AppSetting.ScheduledReportEnabled,
        type: SettingType.BOOLEAN,
        packageValue: false,
        required: true,
        public: false,
        i18nLabel: 'Enable Scheduled Reports',
        i18nDescription: 'Enable automatic daily spam reports in the admin channel at the configured time',
    },
    {
        id: AppSetting.ScheduledReportTimezone,
        type: SettingType.SELECT,
        packageValue: 'UTC',
        required: true,
        public: false,
        i18nLabel: 'Scheduled Report Timezone',
        i18nDescription: 'Timezone for the scheduled report time. The report will be sent at the configured HH:MM in this timezone.',
        values: [
            { key: 'UTC', i18nLabel: 'UTC (+00:00)' },
            { key: 'America/New_York', i18nLabel: 'US Eastern (UTC−05:00)' },
            { key: 'America/Chicago', i18nLabel: 'US Central (UTC−06:00)' },
            { key: 'America/Denver', i18nLabel: 'US Mountain (UTC−07:00)' },
            { key: 'America/Los_Angeles', i18nLabel: 'US Pacific (UTC−08:00)' },
            { key: 'Europe/London', i18nLabel: 'London (UTC+00:00)' },
            { key: 'Europe/Berlin', i18nLabel: 'Central Europe (UTC+01:00)' },
            { key: 'Europe/Moscow', i18nLabel: 'Moscow (UTC+03:00)' },
            { key: 'Asia/Dubai', i18nLabel: 'Dubai (UTC+04:00)' },
            { key: 'Asia/Kolkata', i18nLabel: 'India (IST, UTC+05:30)' },
            { key: 'Asia/Shanghai', i18nLabel: 'China (UTC+08:00)' },
            { key: 'Asia/Tokyo', i18nLabel: 'Japan (UTC+09:00)' },
            { key: 'Australia/Sydney', i18nLabel: 'Sydney (UTC+10:00)' },
            { key: 'Pacific/Auckland', i18nLabel: 'New Zealand (UTC+12:00)' },
        ],
    },
    {
        id: AppSetting.RateShortBurst,
        type: SettingType.NUMBER,
        packageValue: 5,
        required: true,
        public: false,
        i18nLabel: 'Rate Limit — Short Burst (30s)',
        i18nDescription: 'Maximum messages allowed in 30 seconds before triggering rate-flood detection (default: 5)',
    },
    {
        id: AppSetting.RateSustained,
        type: SettingType.NUMBER,
        packageValue: 12,
        required: true,
        public: false,
        i18nLabel: 'Rate Limit — Sustained (2 min)',
        i18nDescription: 'Maximum messages allowed in 2 minutes before triggering rate-flood detection (default: 12)',
    },
    {
        id: AppSetting.AiProvider,
        type: SettingType.SELECT,
        packageValue: 'none',
        required: true,
        public: false,
        i18nLabel: 'AI Provider',
        i18nDescription: 'AI provider for generating summaries and insights in the admin channel',
        values: [
            { key: 'none', i18nLabel: 'None (Disabled)' },
            { key: 'gemini', i18nLabel: 'Gemini' },
            { key: 'groq', i18nLabel: 'Groq' },
        ],
    },
    {
        id: AppSetting.AiApiKey,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        i18nLabel: 'AI API Key',
        i18nDescription: 'API key for the selected AI provider (Gemini or Groq)',
    },
    {
        id: AppSetting.AiModel,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        i18nLabel: 'AI Model',
        i18nDescription: 'Model name for AI provider (e.g., gemini-2.0-flash for Gemini, llama-3.3-70b-versatile for Groq)',
    },
];
